name: "Linux CI (Arm)"

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    name: "aarch64 CI"
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      # Declares the repository safe and not under dubious ownership.
      - name: Add repository to git safe directories
        run: git config --global --add safe.directory $GITHUB_WORKSPACE

      - uses: uraimo/run-on-arch-action@v2
        name: Run commands
        id: runcmd
        with:
          arch: aarch64
          distro: ubuntu20.04
          run: |
            uname -a
            echo ::set-output name=uname::$(uname -a)
            apt-get -y update && apt-get install -y --no-install-recommends git gcc g++ cmake ninja-build libssl-dev libcurl4-openssl-dev python3 libpython3-dev python3-pip libblas-dev liblapack-dev 
            mkdir ci && cd ci && git clone --recursive https://github.com/eclipse/xacc && cd xacc && mkdir build && cd build
            cmake -GNinja .. -DXACC_BUILD_TESTS=TRUE -DXACC_BUILD_EXAMPLES=TRUE
            cmake --build . --target install
            ctest --output-on-failure